"""add profile and admin fields to users

Revision ID: b9718c989691
Revises: 001_initial
Create Date: 2026-03-01 19:11:09.379812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9718c989691'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop child/dependent tables first, then parents
    # 1. twin_chat_messages depends on twin_chat_sessions
    op.drop_index('ix_twin_chat_messages_session_id', table_name='twin_chat_messages')
    op.drop_table('twin_chat_messages')

    # 2. experiment_results depends on experiments and twin_profiles
    op.drop_index('ix_experiment_results_experiment_id', table_name='experiment_results')
    op.drop_index('ix_experiment_results_twin_id', table_name='experiment_results')
    op.drop_table('experiment_results')

    # 3. evidence_snippets depends on twin_profiles
    op.drop_index('ix_evidence_snippets_twin_profile_id', table_name='evidence_snippets')
    op.drop_index('ix_evidence_snippets_user_id', table_name='evidence_snippets')
    op.drop_table('evidence_snippets')

    # 4. twin_chat_sessions depends on twin_profiles
    op.drop_index('ix_twin_chat_sessions_created_by', table_name='twin_chat_sessions')
    op.drop_index('ix_twin_chat_sessions_twin_id', table_name='twin_chat_sessions')
    op.drop_table('twin_chat_sessions')

    # 5. experiments depends on cohorts
    op.drop_index('ix_experiments_cohort_id', table_name='experiments')
    op.drop_index('ix_experiments_created_by', table_name='experiments')
    op.drop_table('experiments')

    # 6. Now drop parent tables
    op.drop_index('ix_twin_profiles_user_id', table_name='twin_profiles')
    op.drop_table('twin_profiles')
    op.drop_index('ix_cohorts_created_by', table_name='cohorts')
    op.drop_table('cohorts')

    # Add new user columns
    op.add_column('users', sa.Column('sex', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'age')
    op.drop_column('users', 'sex')
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cohort_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scenario', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('aggregate_results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name='experiments_cohort_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='experiments_created_by_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='experiments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_experiments_created_by', 'experiments', ['created_by'], unique=False)
    op.create_index('ix_experiments_cohort_id', 'experiments', ['cohort_id'], unique=False)
    op.create_table('twin_chat_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('evidence_used', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('coverage_gaps', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('model_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['twin_chat_sessions.id'], name='twin_chat_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='twin_chat_messages_pkey')
    )
    op.create_index('ix_twin_chat_messages_session_id', 'twin_chat_messages', ['session_id'], unique=False)
    op.create_table('evidence_snippets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('twin_profile_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('module_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('turn_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snippet_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('snippet_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True),
    sa.Column('snippet_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['interview_turns.id'], name='evidence_snippets_turn_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['twin_profile_id'], ['twin_profiles.id'], name='evidence_snippets_twin_profile_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='evidence_snippets_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='evidence_snippets_pkey')
    )
    op.create_index('ix_evidence_snippets_user_id', 'evidence_snippets', ['user_id'], unique=False)
    op.create_index('ix_evidence_snippets_twin_profile_id', 'evidence_snippets', ['twin_profile_id'], unique=False)
    op.create_table('twin_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('modules_included', postgresql.ARRAY(sa.VARCHAR(length=10)), autoincrement=False, nullable=False),
    sa.Column('quality_label', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('structured_profile_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('persona_summary_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('persona_full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coverage_confidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extraction_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='twin_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='twin_profiles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_twin_profiles_user_id', 'twin_profiles', ['user_id'], unique=False)
    op.create_table('experiment_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('twin_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('choice', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence_label', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('evidence_used', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('coverage_gaps', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('model_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name='experiment_results_experiment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['twin_id'], ['twin_profiles.id'], name='experiment_results_twin_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='experiment_results_pkey')
    )
    op.create_index('ix_experiment_results_twin_id', 'experiment_results', ['twin_id'], unique=False)
    op.create_index('ix_experiment_results_experiment_id', 'experiment_results', ['experiment_id'], unique=False)
    op.create_table('cohorts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('twin_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=False),
    sa.Column('filters_used', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='cohorts_created_by_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cohorts_pkey')
    )
    op.create_index('ix_cohorts_created_by', 'cohorts', ['created_by'], unique=False)
    op.create_table('twin_chat_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('twin_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='twin_chat_sessions_created_by_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['twin_id'], ['twin_profiles.id'], name='twin_chat_sessions_twin_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='twin_chat_sessions_pkey')
    )
    op.create_index('ix_twin_chat_sessions_twin_id', 'twin_chat_sessions', ['twin_id'], unique=False)
    op.create_index('ix_twin_chat_sessions_created_by', 'twin_chat_sessions', ['created_by'], unique=False)
    # ### end Alembic commands ###
