"""Step 2 — Concept Board Builder service."""

import copy
import json
import uuid
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.llm.client import LLMClient, get_llm_client
from app.models.concept import Concept
from app.models.study import StepVersion, Study
from app.schemas.concept import (
    ComparabilityCheckResponse,
    ConceptRefineResponse,
    ConceptResponse,
)
from app.services.prompt_service import PromptService, get_prompt_service
from app.services.state_machine import StudyStateMachine


# ---------------------------------------------------------------------------
# Default template components used when generating empty concept shells
# ---------------------------------------------------------------------------
DEFAULT_TEMPLATE_COMPONENTS = {
    "consumer_insight": {
        "raw_input": "",
        "refined": None,
        "refinement_rationale": None,
        "approved": False,
        "brand_edit": None,
    },
    "product_name": {
        "raw_input": "",
        "refined": None,
        "refinement_rationale": None,
        "approved": False,
        "brand_edit": None,
    },
    "key_benefit": {
        "raw_input": "",
        "refined": None,
        "refinement_rationale": None,
        "approved": False,
        "brand_edit": None,
    },
    "reasons_to_believe": {
        "raw_input": "",
        "refined": None,
        "refinement_rationale": None,
        "approved": False,
        "brand_edit": None,
    },
    "visual": {
        "description": "",
        "refined_description": None,
        "refinement_rationale": None,
    },
    "price_format": {
        "price": "",
        "format": "",
        "refined_price": None,
        "refinement_rationale": None,
    },
}

# Number of concept templates generated by default
DEFAULT_NUM_CONCEPTS = 3


class ConceptBoardService:
    """Orchestrates Step 2 (Concept Board Builder) workflows."""

    def __init__(
        self,
        llm_client: LLMClient | None = None,
        prompt_service: PromptService | None = None,
    ):
        self.llm = llm_client or get_llm_client()
        self.prompts = prompt_service or get_prompt_service()

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------

    async def _get_study(self, study_id: uuid.UUID, db: AsyncSession) -> Study:
        result = await db.execute(select(Study).where(Study.id == study_id))
        study = result.scalar_one_or_none()
        if study is None:
            raise ValueError(f"Study {study_id} not found")
        return study

    async def _get_concept(
        self, study_id: uuid.UUID, concept_id: uuid.UUID, db: AsyncSession
    ) -> Concept:
        result = await db.execute(
            select(Concept).where(
                Concept.id == concept_id, Concept.study_id == study_id
            )
        )
        concept = result.scalar_one_or_none()
        if concept is None:
            raise ValueError(
                f"Concept {concept_id} not found for study {study_id}"
            )
        return concept

    async def _get_locked_brief(
        self, study_id: uuid.UUID, db: AsyncSession
    ) -> dict:
        """Return the content dict from the locked step-1 StepVersion."""
        result = await db.execute(
            select(StepVersion).where(
                StepVersion.study_id == study_id,
                StepVersion.step == 1,
                StepVersion.status == "locked",
            )
        )
        sv = result.scalar_one_or_none()
        if sv is None:
            raise ValueError(
                f"No locked step-1 brief found for study {study_id}"
            )
        return sv.content

    @staticmethod
    def _safe_uuid(value: str) -> uuid.UUID | None:
        try:
            return uuid.UUID(value) if isinstance(value, str) else value
        except ValueError:
            return None

    @staticmethod
    def _concept_to_response(concept: Concept) -> ConceptResponse:
        return ConceptResponse(
            id=concept.id,
            study_id=concept.study_id,
            concept_index=concept.concept_index,
            version=concept.version,
            status=concept.status,
            components=concept.components,
            comparability_flags=concept.comparability_flags,
            image_url=concept.image_url,
            created_at=concept.created_at,
        )

    # ------------------------------------------------------------------
    # list_concepts
    # ------------------------------------------------------------------

    async def list_concepts(
        self,
        study_id: uuid.UUID,
        db: AsyncSession,
    ) -> list[ConceptResponse]:
        """Return all concepts for a study, ordered by concept_index."""
        await self._get_study(study_id, db)  # validate study exists
        result = await db.execute(
            select(Concept)
            .where(Concept.study_id == study_id)
            .order_by(Concept.concept_index)
        )
        concepts = list(result.scalars().all())
        return [self._concept_to_response(c) for c in concepts]

    # ------------------------------------------------------------------
    # generate_templates
    # ------------------------------------------------------------------

    async def generate_templates(
        self,
        study_id: uuid.UUID,
        db: AsyncSession,
        num_concepts: int = DEFAULT_NUM_CONCEPTS,
    ) -> list[ConceptResponse]:
        """Create N empty concept records with template components.

        Pre-conditions:
        - Step 1 must be locked (study status == step_1_locked).

        Side-effects:
        - Creates Concept rows in the DB.
        - Transitions study status to step_2_draft.
        """
        study = await self._get_study(study_id, db)

        # Validate step 1 is locked
        if not StudyStateMachine.can_start_step(study, 2):
            raise ValueError(
                f"Cannot generate concepts: study must be in step_1_locked status, "
                f"currently '{study.status}'"
            )

        # Load the locked brief (validates it exists)
        await self._get_locked_brief(study_id, db)

        # Transition study to step_2_draft
        StudyStateMachine.transition(study, "step_2_draft")

        concepts: list[Concept] = []
        for idx in range(num_concepts):
            concept = Concept(
                study_id=study_id,
                concept_index=idx + 1,
                version=1,
                status="raw",
                components=copy.deepcopy(DEFAULT_TEMPLATE_COMPONENTS),
                comparability_flags=[],
                image_url=None,
                image_version=0,
            )
            db.add(concept)
            concepts.append(concept)

        await db.commit()
        for c in concepts:
            await db.refresh(c)

        return [self._concept_to_response(c) for c in concepts]

    # ------------------------------------------------------------------
    # add_concept
    # ------------------------------------------------------------------

    async def add_concept(
        self,
        study_id: uuid.UUID,
        db: AsyncSession,
    ) -> ConceptResponse:
        """Add a single new concept board to an existing study.

        Pre-conditions:
        - Study must be in step_2_draft or step_2_review status.
        """
        study = await self._get_study(study_id, db)

        # Allow adding concepts from step_1_locked (auto-transition to step_2_draft)
        if study.status == "step_1_locked":
            StudyStateMachine.transition(study, "step_2_draft")
        elif study.status not in ("step_2_draft", "step_2_review"):
            raise ValueError(
                f"Cannot add concept: study must be in step_1_locked, step_2_draft, or step_2_review, "
                f"currently '{study.status}'"
            )

        # Find the next concept_index
        result = await db.execute(
            select(Concept).where(Concept.study_id == study_id).order_by(Concept.concept_index.desc())
        )
        last_concept = result.scalars().first()
        next_index = (last_concept.concept_index + 1) if last_concept else 1

        concept = Concept(
            study_id=study_id,
            concept_index=next_index,
            version=1,
            status="raw",
            components=copy.deepcopy(DEFAULT_TEMPLATE_COMPONENTS),
            comparability_flags=[],
            image_url=None,
            image_version=0,
        )
        db.add(concept)
        await db.commit()
        await db.refresh(concept)

        return self._concept_to_response(concept)

    # ------------------------------------------------------------------
    # update_concept
    # ------------------------------------------------------------------

    async def update_concept(
        self,
        study_id: uuid.UUID,
        concept_id: uuid.UUID,
        components: dict,
        db: AsyncSession,
    ) -> ConceptResponse:
        """Update concept components (raw edit by the user).

        Pre-conditions:
        - Step 2 must NOT be locked.
        """
        study = await self._get_study(study_id, db)

        if StudyStateMachine.is_step_locked(study, 2):
            raise ValueError("Cannot update concept: step 2 is locked")

        concept = await self._get_concept(study_id, concept_id, db)
        concept.components = components
        concept.version += 1
        # Status stays "raw"
        await db.commit()
        await db.refresh(concept)
        return self._concept_to_response(concept)

    # ------------------------------------------------------------------
    # refine_concept
    # ------------------------------------------------------------------

    async def refine_concept(
        self,
        study_id: uuid.UUID,
        concept_id: uuid.UUID,
        db: AsyncSession,
    ) -> ConceptRefineResponse:
        """Refine a single concept via LLM.

        Pre-conditions:
        - Concept must exist and be in 'raw' status.
        """
        study = await self._get_study(study_id, db)
        concept = await self._get_concept(study_id, concept_id, db)

        if concept.status not in ("raw", "refined", "approved"):
            raise ValueError(
                f"Concept must be in 'raw', 'refined', or 'approved' status to refine, currently '{concept.status}'"
            )

        # Gather context from the study brief
        brief = await self._get_locked_brief(study_id, db)
        category = study.category or brief.get("category", "unknown")
        study_type = brief.get("study_type", "concept_testing")
        competitor_brands = study.context.get("competitor_brands", "N/A") if study.context else "N/A"
        if isinstance(competitor_brands, list):
            competitor_brands = ", ".join(competitor_brands)

        prompt = self.prompts.format_prompt(
            "concept_refiner",
            brand_name=study.brand_name or "Unknown",
            category=category,
            study_type=study_type,
            competitor_brands=str(competitor_brands),
            raw_concept_json=json.dumps(concept.components, indent=2),
        )

        llm_result = await self.llm.generate_json(prompt)

        # Merge refined data back into concept components
        refined_components = llm_result.get("refined_components", {})
        merged = copy.deepcopy(concept.components)
        for key, refinement in refined_components.items():
            if key in merged and isinstance(merged[key], dict):
                merged[key].update(refinement)

        concept.components = merged
        concept.status = "refined"
        await db.commit()
        await db.refresh(concept)

        return ConceptRefineResponse(
            concept_id=concept.id,
            refined_components=refined_components,
            flags=llm_result.get("flags", []),
            testability_score=float(llm_result.get("testability_score", 0.0)),
        )

    # ------------------------------------------------------------------
    # approve_concept
    # ------------------------------------------------------------------

    async def approve_concept(
        self,
        study_id: uuid.UUID,
        concept_id: uuid.UUID,
        approved_components: dict,
        db: AsyncSession,
    ) -> ConceptResponse:
        """Accept refined or brand-edit for each component, setting status to approved.

        `approved_components` maps component keys to the chosen version:
        e.g. {"consumer_insight": "refined", "product_name": "brand_edit", ...}
        or provides direct overrides as dicts.
        """
        concept = await self._get_concept(study_id, concept_id, db)

        merged = copy.deepcopy(concept.components)
        for key, value in approved_components.items():
            if key in merged and isinstance(merged[key], dict):
                if isinstance(value, dict):
                    # Direct override of the component
                    merged[key].update(value)
                    merged[key]["approved"] = True
                elif value == "refined":
                    merged[key]["approved"] = True
                elif value == "brand_edit":
                    merged[key]["approved"] = True
                else:
                    merged[key]["approved"] = True

        concept.components = merged
        concept.status = "approved"
        await db.commit()
        await db.refresh(concept)
        return self._concept_to_response(concept)

    # ------------------------------------------------------------------
    # comparability_check
    # ------------------------------------------------------------------

    async def comparability_check(
        self,
        study_id: uuid.UUID,
        db: AsyncSession,
    ) -> ComparabilityCheckResponse:
        """Run a comparability audit across ALL concepts for a study."""
        # Load all concepts
        result = await db.execute(
            select(Concept).where(Concept.study_id == study_id).order_by(Concept.concept_index)
        )
        concepts = list(result.scalars().all())

        if not concepts:
            raise ValueError(f"No concepts found for study {study_id}")

        all_concepts_payload = [
            {
                "concept_index": c.concept_index,
                "status": c.status,
                "components": c.components,
            }
            for c in concepts
        ]

        # Get study context for the auditor
        study = await self._get_study(study_id, db)
        brief = await self._get_locked_brief(study_id, db)
        category = study.category or brief.get("category", "unknown")
        study_type = brief.get("study_type", "concept_testing")

        prompt = self.prompts.format_prompt(
            "comparability_auditor",
            category=category,
            study_type=study_type,
            all_concepts_json=json.dumps(all_concepts_payload, indent=2),
        )

        llm_result = await self.llm.generate_json(prompt)

        overall = llm_result.get("overall_comparability", "warning")
        issues = llm_result.get("issues", [])
        recommendation = llm_result.get("recommendation", "")

        # Store comparability flags on each concept
        for concept in concepts:
            concept.comparability_flags = issues
        await db.commit()

        return ComparabilityCheckResponse(
            overall_comparability=overall,
            issues=issues,
            recommendation=recommendation,
        )

    # ------------------------------------------------------------------
    # render_image
    # ------------------------------------------------------------------

    async def render_image(
        self,
        study_id: uuid.UUID,
        concept_id: uuid.UUID,
        db: AsyncSession,
    ) -> ConceptResponse:
        """Generate a placeholder image URL for a concept."""
        concept = await self._get_concept(study_id, concept_id, db)

        concept.image_version += 1
        concept.image_url = (
            f"https://storage.darpan.ai/studies/{study_id}/concepts/"
            f"{concept_id}/render_v{concept.image_version}.png"
        )

        await db.commit()
        await db.refresh(concept)
        return self._concept_to_response(concept)

    # ------------------------------------------------------------------
    # lock_concepts
    # ------------------------------------------------------------------

    async def lock_concepts(
        self,
        study_id: uuid.UUID,
        user_id: str,
        db: AsyncSession,
    ) -> dict:
        """Lock step 2 after validating all concepts are approved.

        Pre-conditions:
        - ALL concepts must be in 'approved' status.
        - Study must be in step_2_review status (or transitionable to step_2_locked).

        Side-effects:
        - Creates a StepVersion record for step=2.
        - Transitions study to step_2_locked.
        """
        study = await self._get_study(study_id, db)

        # If still in step_2_draft, transition to step_2_review first
        if study.status == "step_2_draft":
            StudyStateMachine.transition(study, "step_2_review")

        # Load all concepts
        result = await db.execute(
            select(Concept).where(Concept.study_id == study_id).order_by(Concept.concept_index)
        )
        concepts = list(result.scalars().all())

        if not concepts:
            raise ValueError(f"No concepts found for study {study_id}")

        # Validate ALL concepts are approved
        unapproved = [
            c.concept_index for c in concepts if c.status != "approved"
        ]
        if unapproved:
            raise ValueError(
                f"Cannot lock step 2: concepts at indices {unapproved} are not approved"
            )

        # Lock the step via state machine
        StudyStateMachine.lock_step(study, 2, user_id)

        # Create StepVersion snapshot
        step_content = {
            "concepts": [
                {
                    "concept_id": str(c.id),
                    "concept_index": c.concept_index,
                    "version": c.version,
                    "status": c.status,
                    "components": c.components,
                    "image_url": c.image_url,
                }
                for c in concepts
            ]
        }

        # Determine next version number
        existing = await db.execute(
            select(StepVersion).where(
                StepVersion.study_id == study_id, StepVersion.step == 2
            )
        )
        existing_versions = list(existing.scalars().all())
        next_version = max((sv.version for sv in existing_versions), default=0) + 1

        step_version = StepVersion(
            study_id=study_id,
            step=2,
            version=next_version,
            status="locked",
            content=step_content,
            locked_at=datetime.now(timezone.utc),
            locked_by=self._safe_uuid(user_id),
        )
        db.add(step_version)

        await db.commit()
        await db.refresh(step_version)

        return {
            "study_id": str(study_id),
            "step": 2,
            "version": step_version.version,
            "status": "locked",
            "locked_at": step_version.locked_at.isoformat() if step_version.locked_at else None,
            "locked_by": user_id,
            "num_concepts": len(concepts),
        }
